version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  postgres:
    image: postgres:9.5-alpine
    ports:
      - "5432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    volumes:
      - ./work/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"