server:
  port: 7788
spring:
  r2dbc:
    protocol: r2dbc:postgresql
    host: localhost
    port: 5432
    username: postgres
    password:
    database: foyo_bi_db
    pool:
      max-size: 20
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
foyo:
  bi:
    version: 1.0.0-alpha
