[versions]
kotlin = "1.8.0"
dataframe = "0.9.1"
mysql = "8.0.30"
arrow = "10.0.0"
junit = "4.13.2"
postgresql = "42.3.8"

[libraries]
dataframe = { group = "org.jetbrains.kotlinx", name = "dataframe", version.ref = "dataframe" }
mysql = { group = "mysql", name = "mysql-connector-java", version.ref = "mysql" }
postgresql= { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
arrow-format = { group = "org.apache.arrow", name = "arrow-format", version.ref = "arrow" }
arrow-vector = { group = "org.apache.arrow", name = "arrow-vector", version.ref = "arrow" }
arrow-memory = { group = "org.apache.arrow", name = "arrow-memory-unsafe", version.ref = "arrow" }
arrow-jdbc = { group = "org.apache.arrow", name = "arrow-jdbc", version.ref = "arrow" }

junit = { module = "junit:junit", version.ref = "junit" }
